/thermal_DS4025FT/thermal_camera_to_world:
  ros__parameters:
    Alert_Waiting_Time: 5
    Thermal_LowerLeft:
    - 51
    - 1005
    Thermal_LowerRight:
    - 141
    - 196
    Thermal_UpperLeft:
    - 1211
    - 983
    Thermal_UpperRight:
    - 1227
    - 151
    Threshold_Temperature: 50.0
    World_LowerLeft:
    - 4.01
    - 7.87
    World_LowerRight:
    - 7.16
    - 8.85
    World_UpperLeft:
    - 4.72
    - 5.74
    World_UpperRight:
    - 8.2
    - 6.25
/thermal_IPT430M/thermal_camera_to_world:
  ros__parameters:
    Alert_Waiting_Time: 5
    Thermal_LowerLeft:
    - 495
    - 348
    Thermal_LowerRight:
    - 469
    - 85
    Thermal_UpperLeft:
    - 13
    - 376
    Thermal_UpperRight:
    - 53
    - 64
    Threshold_Temperature: 50.0
    World_LowerLeft:
    - 5.54
    - 1.0
    World_LowerRight:
    - 10.21
    - 4.13
    World_UpperLeft:
    - 1.54
    - 4.34
    World_UpperRight:
    - 5.64
    - 10.13
