/thermal_DS4025FT/thermal_camera_to_world:
  ros__parameters:
    Alert_Waiting_Time: 5
    Thermal_LowerLeft:
    - 1216
    - 1003
    Thermal_LowerRight:
    - 1179
    - 184
    Thermal_UpperLeft:
    - 127
    - 956
    Thermal_UpperRight:
    - 209
    - 244
    Threshold_Temperature: 50.0
    World_LowerLeft:
    - 5.4
    - 3.2
    World_LowerRight:
    - 8.9
    - 2.6
    World_UpperLeft:
    - 5.7
    - 5.3
    World_UpperRight:
    - 8.5
    - 5.1
/thermal_IPT430M/thermal_camera_to_world:
  ros__parameters:
    Alert_Waiting_Time: 5
    Thermal_LowerLeft:
    - 54
    - 27
    Thermal_LowerRight:
    - 483
    - 54
    Thermal_UpperLeft:
    - 105
    - 342
    Thermal_UpperRight:
    - 476
    - 329
    Threshold_Temperature: 50.0
    World_LowerLeft:
    - 20.0
    - 50.0
    World_LowerRight:
    - 6.0
    - 8.0
    World_UpperLeft:
    - 1.0
    - 1.0
    World_UpperRight:
    - 3.0
    - 3.0
