/thermal_DS4025FT/thermal_camera_to_world:
  ros__parameters:
    Alert_Waiting_Time: 5
    Thermal_LowerLeft:
    - 1216
    - 1003
    Thermal_LowerRight:
    - 1179
    - 184
    Thermal_UpperLeft:
    - 127
    - 956
    Thermal_UpperRight:
    - 209
    - 244
    Threshold_Temperature: 50.0
    World_LowerLeft:
    - 5.4
    - 3.2
    World_LowerRight:
    - 8.9
    - 2.6
    World_UpperLeft:
    - 5.7
    - 5.3
    World_UpperRight:
    - 8.5
    - 5.1
/thermal_IPT430M/thermal_camera_to_world:
  ros__parameters:
    Alert_Waiting_Time: 5
    Thermal_LowerLeft:
    - 155
    - 89
    Thermal_LowerRight:
    - 43
    - 358
    Thermal_UpperLeft:
    - 443
    - 104
    Thermal_UpperRight:
    - 460
    - 379
    Threshold_Temperature: 50.0
    World_LowerLeft:
    - 7.3
    - 9.2
    World_LowerRight:
    - 2.3
    - 5.8
    World_UpperLeft:
    - 9.5
    - 4.6
    World_UpperRight:
    - 4.8
    - 1.5
