/thermal_DS4025FT/thermal_camera_to_world:
  ros__parameters:
    Alert_Waiting_Time: 5
    Thermal_LowerLeft:
    - 125
    - 69
    Thermal_LowerRight:
    - 1147
    - 62
    Thermal_UpperLeft:
    - 53
    - 949
    Thermal_UpperRight:
    - 1205
    - 955
    Threshold_Temperature: 60.0
    World_LowerLeft:
    - 3.0
    - 3.0
    World_LowerRight:
    - 5.0
    - 5.0
    World_UpperLeft:
    - 5.0
    - 5.0
    World_UpperRight:
    - 1.0
    - 1.0
/thermal_IPT430M/thermal_camera_to_world:
  ros__parameters:
    Alert_Waiting_Time: 5
    Thermal_LowerLeft:
    - 45
    - 33
    Thermal_LowerRight:
    - 477
    - 32
    Thermal_UpperLeft:
    - 57
    - 346
    Thermal_UpperRight:
    - 483
    - 337
    Threshold_Temperature: 60.0
    World_LowerLeft:
    - 5.0
    - 5.0
    World_LowerRight:
    - 3.0
    - 3.0
    World_UpperLeft:
    - 5.0
    - 5.0
    World_UpperRight:
    - 1.0
    - 1.0
