/thermal_DS4025FT/thermal_camera_to_world:
  ros__parameters:
    Alert_Waiting_Time: 5
    Thermal_LowerLeft:
    - 51
    - 1005
    Thermal_LowerRight:
    - 141
    - 196
    Thermal_UpperLeft:
    - 1211
    - 983
    Thermal_UpperRight:
    - 1227
    - 151
    Threshold_Temperature: 60.0
    World_LowerLeft:
    - 4.01
    - 7.87
    World_LowerRight:
    - 7.16
    - 8.85
    World_UpperLeft:
    - 4.72
    - 5.74
    World_UpperRight:
    - 8.2
    - 6.25
/thermal_IPT430M/thermal_camera_to_world:
  ros__parameters:
    Alert_Waiting_Time: 5
    Thermal_LowerLeft:
    - 481
    - 169
    Thermal_LowerRight:
    - 469
    - 361
    Thermal_UpperLeft:
    - 57
    - 145
    Thermal_UpperRight:
    - 78
    - 362
    Threshold_Temperature: 60.0
    World_LowerLeft:
    - 12.03
    - 3.85
    World_LowerRight:
    - 6.98
    - 1.87
    World_UpperLeft:
    - 7.35
    - 11.01
    World_UpperRight:
    - 4.01
    - 5.08
