/thermal_DS4025FT/thermal_camera_to_world:
  ros__parameters:
    Alert_Waiting_Time: 5
    Thermal_LowerLeft:
    - 1216
    - 1003
    Thermal_LowerRight:
    - 1179
    - 184
    Thermal_UpperLeft:
    - 127
    - 956
    Thermal_UpperRight:
    - 209
    - 244
    Threshold_Temperature: 50.0
    World_LowerLeft:
    - 5.4
    - 3.2
    World_LowerRight:
    - 8.9
    - 2.6
    World_UpperLeft:
    - 5.7
    - 5.3
    World_UpperRight:
    - 8.5
    - 5.1
/thermal_IPT430M/thermal_camera_to_world:
  ros__parameters:
    Alert_Waiting_Time: 5
    Thermal_LowerLeft:
    - 56
    - 34
    Thermal_LowerRight:
    - 463
    - 51
    Thermal_UpperLeft:
    - 60
    - 338
    Thermal_UpperRight:
    - 471
    - 344
    Threshold_Temperature: 50.0
    World_LowerLeft:
    - -0.17127697952930127
    - 0.4300233480276795
    World_LowerRight:
    - -0.17127697952930127
    - 0.4300233480276795
    World_UpperLeft:
    - -0.17127697952930124
    - 0.4300233480276795
    World_UpperRight:
    - -0.17127697952930124
    - 0.4300233480276795
