/thermal_DS4025FT/thermal_camera_to_world:
  ros__parameters:
    Alert_Waiting_Time: 5
    Thermal_LowerLeft:
    - 1028
    - 34
    Thermal_LowerRight:
    - 1226
    - 929
    Thermal_UpperLeft:
    - 116
    - 337
    Thermal_UpperRight:
    - 365
    - 959
    Threshold_Temperature: 80.0
    World_LowerLeft:
    - 9.0
    - 6.0
    World_LowerRight:
    - 8.0
    - 9.0
    World_UpperLeft:
    - 5.0
    - 5.0
    World_UpperRight:
    - 6.0
    - 8.0
/thermal_IPT430M/thermal_camera_to_world:
  ros__parameters:
    Alert_Waiting_Time: 5
    Thermal_LowerLeft:
    - 10
    - 376
    Thermal_LowerRight:
    - 506
    - 379
    Thermal_UpperLeft:
    - 174
    - 90
    Thermal_UpperRight:
    - 155
    - 313
    Threshold_Temperature: 80.0
    World_LowerLeft:
    - 7.0
    - 80.0
    World_LowerRight:
    - 5.0
    - 23.0
    World_UpperLeft:
    - 15.2
    - 22.0
    World_UpperRight:
    - 10.0
    - 100.0
