/thermal_camera_to_world:
  ros__parameters:
    World_UpperLeft: [0.0, 21.0]
    World_UpperRight: [29.7, 21.0]
    World_LowerRight: [29.7, 0.0]
    World_LowerLeft: [0.0, 0.0]
    Threshold_Temperature: 80.0
    Alert_Waiting_Time: 5

  # ds4025ft:
  #   UpperLeft: [0.0, 0.0]
  #   UpperRight: [0.0, 0.0]
  #   LowerRight: [0.0, 0.0]
  #   LowerLeft: [0.0, 0.0]

