thermal_camera_to_world:
  ipt430m:
    UpperLeft: [1.19, 3.35]
    UpperRight: [3.61, 2.05]
    LowerRight: [1.50, 0.62]
    LowerLeft: [0.40, 1.50]

  ds4025ft:
    UpperLeft: [0.0, 0.0]
    UpperRight: [0.0, 0.0]
    LowerRight: [0.0, 0.0]
    LowerLeft: [0.0, 0.0]

