/thermal_DS4025FT/thermal_camera_to_world:
  ros__parameters:
    Alert_Waiting_Time: 5
    Thermal_LowerLeft:
    - 1219
    - 987
    Thermal_LowerRight:
    - 1104
    - 424
    Thermal_UpperLeft:
    - 34
    - 1005
    Thermal_UpperRight:
    - 44
    - 418
    Threshold_Temperature: 60.0
    World_LowerLeft:
    - 6.1
    - 3.0
    World_LowerRight:
    - 8.4
    - 3.0
    World_UpperLeft:
    - 6.0
    - 5.4
    World_UpperRight:
    - 8.4
    - 5.5
/thermal_IPT430M/thermal_camera_to_world:
  ros__parameters:
    Alert_Waiting_Time: 5
    Thermal_LowerLeft:
    - 429
    - 365
    Thermal_LowerRight:
    - 431
    - 126
    Thermal_UpperLeft:
    - 37
    - 354
    Thermal_UpperRight:
    - 74
    - 77
    Threshold_Temperature: 60.0
    World_LowerLeft:
    - 5.3
    - 1.6
    World_LowerRight:
    - 9.0
    - 3.9
    World_UpperLeft:
    - 2.6
    - 4.7
    World_UpperRight:
    - 6.68
    - 9.5
