ipt430m:
  UpperLeft:
    - [1.19, 3.35, -1.50]
  UpperRight:
    - [3.61, 2.05, -1.40]
  LowerRight:
    - [1.50, 0.62, -1.70]
  LowerLeft: 
    - [0.40, 1.50, -1.35]

ds4025ft:
  UpperLeft:
    - [0.0, 0.0, 0.0]
  UpperRight:
    - [0.0, 0.0, 0.0]
  LowerRight:
    - [0.0, 0.0, 0.0]
  LowerLeft: 
    - [0.0, 0.0, 0.0]