/thermal_DS4025FT/uwb_experiment:
  ros__parameters:
    Alert_Waiting_Time: 5
    Thermal_LowerLeft:
    - 1216
    - 1003
    Thermal_LowerRight:
    - 1179
    - 184
    Thermal_UpperLeft:
    - 127
    - 956
    Thermal_UpperRight:
    - 209
    - 244
    Threshold_Temperature: 50.0
    World_LowerLeft:
    - 5.4
    - 3.2
    World_LowerRight:
    - 8.9
    - 2.6
    World_UpperLeft:
    - 5.7
    - 5.3
    World_UpperRight:
    - 8.5
    - 5.1
/thermal_IPT430M/uwb_experiment:
  ros__parameters:
    Alert_Waiting_Time: 5
    Thermal_LowerLeft:
    - 54
    - 54
    Thermal_LowerRight:
    - 475
    - 68
    Thermal_UpperLeft:
    - 76
    - 345
    Thermal_UpperRight:
    - 494
    - 358
    Threshold_Temperature: 50.0
    World_LowerLeft:
    - 0.0
    - 5.0
    World_LowerRight:
    - 5.0
    - 5.0
    World_UpperLeft:
    - 0.0
    - 0.0
    World_UpperRight:
    - 5.0
    - 0.0
